server:
  port: 10001
  servlet:
    context-path: /
apollo:
  bootstrap:
    enabled: true
app:
  id: 1001
logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  application:
    name: dh-gateway
  profiles:
    active: dev
---
spring:
  profiles: dev

apollo:
  meta: http://localhost:8080
---
spring:
  profiles: test